### ISSUE TITLE
Yarn don't work in docker

### ISSUE THREAD

**Issue by Raphitpt** [hmerritt/android-sdk#4]
Hi, when i would build my app with expo or when i make yarn install, i have this error : 
```shell
[INSTALL_DEPENDENCIES] Running "yarn install" in /tmp/root/eas-build-local-nodejs/71e1ce44-04fb-4eb6-bd89-d19ad269667e/build directory
[INSTALL_DEPENDENCIES] Usage Error: The nearest package directory (/tmp/root/eas-build-local-nodejs/71e1ce44-04fb-4eb6-bd89-d19ad269667e/build) doesn't seem to be part of the project declared in /.
[INSTALL_DEPENDENCIES]
[INSTALL_DEPENDENCIES] - If / isn't intended to be a project, remove any yarn.lock and/or package.json file there.
[INSTALL_DEPENDENCIES] - If / is intended to be a project, it might be that you forgot to list tmp/root/eas-build-local-nodejs/71e1ce44-04fb-4eb6-bd89-d19ad269667e/build in its workspace configuration.
[INSTALL_DEPENDENCIES] - Finally, if / is fine and you intend tmp/root/eas-build-local-nodejs/71e1ce44-04fb-4eb6-bd89-d19ad269667e/build to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
[INSTALL_DEPENDENCIES]
[INSTALL_DEPENDENCIES] $ yarn install [--json] [--immutable] [--immutable-cache] [--refresh-lockfile] [--check-cache] [--check-resolutions] [--inline-builds] [--mode #0]
[INSTALL_DEPENDENCIES]
Error: yarn install exited with non-zero code: 1
    at ChildProcess.completionListener (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at installDependenciesAsync (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/common/installDependencies.js:24:50)
    at async runInstallDependenciesAsync (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/common/setup.js:148:50)
    at async /root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/common/setup.js:57:9
    at async BuildContext.runBuildPhase (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/context.js:107:28)
    at async setupAsync (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/common/setup.js:56:5)
    at async buildAsync (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/builders/android.js:38:5)
    at async runBuilderWithHooksAsync (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.androidBuilder (/root/.npm/_npx/93986e4ba4ec11e8/node_modules/@expo/build-tools/dist/builders/android.js:24:16)

Build failed
Unknown error. See logs of the Install dependencies build phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
```

**Comment by hmerritt** [comment]
Hello - I see you've closed this issue, but just to double-check, do you still need help with this or did you manage to solve it already?
