### ISSUE TITLE
Unable to build using yarn 

### ISSUE THREAD

**Issue by XChikuX** [hmerritt/android-sdk#5]
I have WSL installed with Docker Desktop.

The container is downloaded from docker hub on run. But I get this:

```ps
PS C:\Code\New-Elysium\Psync> yarn docker-apk
Syntax Error: Expected ":+", ":+}", ":-", ":-}", "}", or [$@*?#a-zA-Z0-9_\-] but ":" found (line 1, column 24).
    at UA (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:12:3214)
    at X_e (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:12:22154)
    at uP (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:12:22327)
    at ky (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:168:1973)
    at b (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:189:2755)
    at C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:189:2939
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _n.mktempPromise (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:9:45513)
    at async Object.Db (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:189:2568)
    at async qE.execute (C:\Code\New-Elysium\Psync\.yarn\releases\yarn-4.5.3.cjs:518:516)
```

**Comment by hmerritt** [comment]
Hello 👋, I will let to help debug:

- You say you are using WSL, but the logs are from Powershell (windows) - you need to be running the commands within the container

- If the above is intentional, and you want to start the container to build with a yarn command, and yarn is failing, them presumably it's a problem with your local repo / environment setup.

It would be useful to know what command `yarn docker-apk` actually running

**Comment by XChikuX** [comment]
```
scripts {
    "docker-apk": "docker run -it -v ${env:PWD}:/project/app hmerritt/android-sdk eas build --local --platform android --profile development"
  }
```

**Comment by hmerritt** [comment]
I am convinced this is a problem with yarn / the repo and not with this project.

`yarn` is failing before the command is being ran.

I think it's most likely the `${env:PWD}` part of the command - I don't think this is valid syntax and that's why it's failing.

You can probably replace it with `./`
